Initial commit from original zip.
As it was on
http://www.cpctech.org.uk/download/addhead.zip
which was then redirected to
http://cpctech.cpcwiki.de/download/addhead.zip
which then had an invalid certificate.

LC_ALL=C wget -nv http://cpctech.cpcwiki.de/download/addhead.zip

ERROR: cannot verify cpctech.cpcwiki.de's certificate, issued by 'emailAddress=info@plesk.com,CN=Plesk,O=Plesk,L=Schaffhausen,C=CH':
  Self-signed certificate encountered.
    ERROR: certificate common name 'Plesk' doesn't match requested host name 'cpctech.cpcwiki.de'.
To connect to cpctech.cpcwiki.de insecurely, use `--no-check-certificate'.